// Generated by scripts/generate-strings.py. DO NOT EDIT.
// Edit i18n/strings.yaml instead and re-run the generator.

import Foundation

/// Translations of the SDK's permission-alert strings, embedded in
/// Swift source so the SDK never has to resolve a resource bundle.
///
/// Historically these lived as `.lproj/Localizable.strings` files inside
/// `Platinumaps.bundle`. Carrying them as a resource breaks the Flutter
/// plugin's Swift Package Manager build, because Flutter's plugin
/// injection treats the plugin package as a local override of an
/// ephemeral copy that ALSO declares the same resource files — Xcode
/// then refuses to resolve the package graph with "duplicate rule"
/// errors. Embedding the strings sidesteps that entirely and keeps the
/// SDK self-contained for every distribution channel (Swift Package
/// Manager, CocoaPods, manual integration, Flutter plugin).
enum PMLocalizedStrings {

    static func string(forKey key: String) -> String {
        let identifier = Bundle.main.preferredLocalizations.first
            ?? Locale.current.identifier
        let table = table(forLanguageCode: identifier)
        return table[key] ?? englishTable[key] ?? key
    }

    private static func table(forLanguageCode code: String) -> [String: String] {
        let primary = code.split(separator: "-").first.map(String.init)?.lowercased() ?? ""
        switch primary {
        case "ja":
            return japaneseTable
        case "ko":
            return koreanTable
        case "zh":
            // Match Apple's BCP-47 forms (`zh-Hans-…`, `zh-Hant-…`) as well
            // as the older legacy codes (`zh-CN`, `zh-TW`).
            let lowered = code.lowercased()
            if lowered.contains("hant") || lowered.contains("tw") || lowered.contains("hk") || lowered.contains("mo") {
                return traditionalChineseTable
            }
            return simplifiedChineseTable
        default:
            return englishTable
        }
    }

    private static let englishTable: [String: String] = [
        "PMDeniedTitle": "Notice",
        "PMDeniedMessage": "This feature requires location services. Please open the settings and allow the app to access your location.",
        "PMDeniedOk": "Settings",
        "PMDeniedCancel": "Cancel",
        "PMRestrictedTitle": "Location Services Unavailable",
        "PMRestrictedMessage": "Location services are restricted on this device, so the app cannot access your location.",
    ]

    private static let japaneseTable: [String: String] = [
        "PMDeniedTitle": "確認",
        "PMDeniedMessage": "この機能は位置情報を利用します。設定を開いて、アプリに位置情報の利用を許可してください。",
        "PMDeniedOk": "設定を開く",
        "PMDeniedCancel": "キャンセル",
        "PMRestrictedTitle": "位置情報を利用できません",
        "PMRestrictedMessage": "この端末では位置情報の利用が制限されているため、位置情報を利用できません。",
    ]

    private static let koreanTable: [String: String] = [
        "PMDeniedTitle": "확인",
        "PMDeniedMessage": "이 기능은 위치 정보를 사용합니다. 설정을 열어 앱에 위치 정보 사용을 허용해주세요.",
        "PMDeniedOk": "설정 열기",
        "PMDeniedCancel": "취소",
        "PMRestrictedTitle": "위치 정보를 사용할 수 없습니다",
        "PMRestrictedMessage": "이 장치에서는 위치 정보 사용이 제한되어 있어, 위치 정보를 사용할 수 없습니다.",
    ]

    private static let simplifiedChineseTable: [String: String] = [
        "PMDeniedTitle": "确认",
        "PMDeniedMessage": "此功能需要使用位置信息。请打开设置，允许应用访问您的位置信息。",
        "PMDeniedOk": "打开设置",
        "PMDeniedCancel": "取消",
        "PMRestrictedTitle": "无法使用位置信息",
        "PMRestrictedMessage": "此设备的位置信息使用已被限制，无法使用位置信息功能。",
    ]

    private static let traditionalChineseTable: [String: String] = [
        "PMDeniedTitle": "確認",
        "PMDeniedMessage": "此功能需要使用位置信息。請打開設定，允許應用程式訪問您的位置信息。",
        "PMDeniedOk": "打開設定",
        "PMDeniedCancel": "取消",
        "PMRestrictedTitle": "無法使用位置信息",
        "PMRestrictedMessage": "此設備的位置信息使用已被限制，無法使用位置信息功能。",
    ]
}
