name: platinumaps_flutter_sdk
description: Flutter SDK for embedding the Platinumaps web map in a Flutter app.
version: 0.1.0
homepage: https://github.com/boldright/platinumaps-sdk
repository: https://github.com/boldright/platinumaps-sdk/tree/main/Flutter/platinumaps_flutter_sdk
issue_tracker: https://github.com/boldright/platinumaps-sdk/issues

topics:
  - map
  - webview
  - location
  - beacon
  - platinumaps

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: jp.co.boldright.platinumaps.flutter
        pluginClass: PlatinumapsFlutterPlugin
      ios:
        pluginClass: PlatinumapsFlutterPlugin
