#!/usr/bin/env python3
"""Regenerate the per-platform localization files from i18n/strings.yaml.

Outputs:
    iOS/platinumaps-sdk/Types/PMLocalizedStrings.swift
    Android/platinumaps-sdk/src/main/res/values/strings.xml
    Android/platinumaps-sdk/src/main/res/values-ja/strings.xml
    Android/platinumaps-sdk/src/main/res/values-ko/strings.xml
    Android/platinumaps-sdk/src/main/res/values-b+zh+Hans/strings.xml
    Android/platinumaps-sdk/src/main/res/values-b+zh+Hant/strings.xml

Run from the repo root after editing `i18n/strings.yaml`:

    python3 scripts/generate-strings.py
"""

from __future__ import annotations

from pathlib import Path
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "PyYAML is required. Install it with:\n"
        "    python3 -m pip install --user pyyaml\n"
    )
    raise SystemExit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = REPO_ROOT / "i18n" / "strings.yaml"

IOS_OUTPUT = REPO_ROOT / "iOS" / "platinumaps-sdk" / "Types" / "PMLocalizedStrings.swift"

# CLAUDE.md requires `Android/platinumaps-sdk/` and
# `Android/sample/platinumaps-sdk/` to stay byte-identical, so the
# generator writes the same XML to both trees.
ANDROID_RES_ROOTS = [
    REPO_ROOT / "Android" / "platinumaps-sdk" / "src" / "main" / "res",
    REPO_ROOT / "Android" / "sample" / "platinumaps-sdk" / "src" / "main" / "res",
]

ANDROID_VALUES_DIRS = {
    "en": "values",
    "ja": "values-ja",
    "ko": "values-ko",
    "zh-Hans": "values-b+zh+Hans",
    "zh-Hant": "values-b+zh+Hant",
}

# The set of languages we generate. `en` is required (used as the
# fallback both sides); the rest are optional per entry but expected.
LANGUAGES = ["en", "ja", "ko", "zh-Hans", "zh-Hant"]

# Maps the language code to the iOS `private static let` table name.
IOS_TABLE_NAMES = {
    "en": "englishTable",
    "ja": "japaneseTable",
    "ko": "koreanTable",
    "zh-Hans": "simplifiedChineseTable",
    "zh-Hant": "traditionalChineseTable",
}


def load_strings() -> list[dict]:
    with YAML_PATH.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    entries = data.get("strings", [])
    for entry in entries:
        translations = entry.get("translations", {})
        if "en" not in translations:
            raise ValueError(
                f"entry missing required English translation: {entry}"
            )
    return entries


def swift_escape(value: str) -> str:
    """Escape a string literal for Swift source."""
    out = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    return "".join(out)


def xml_escape(value: str) -> str:
    """Escape a string for inclusion in an Android resources XML body.

    Android's strings.xml uses & and < as XML metacharacters and treats
    " and ' as literal-string delimiters; the latter must be backslash-
    escaped. \\n inside the YAML is preserved verbatim because Android
    interprets it as a newline at runtime.
    """
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("'", "\\'")
        .replace('"', '\\"')
    )


def render_ios(entries: list[dict]) -> str:
    """Generate the body of `PMLocalizedStrings.swift`."""
    lines = [
        "// Generated by scripts/generate-strings.py. DO NOT EDIT.",
        "// Edit i18n/strings.yaml instead and re-run the generator.",
        "",
        "import Foundation",
        "",
        "/// Translations of the SDK's permission-alert strings, embedded in",
        "/// Swift source so the SDK never has to resolve a resource bundle.",
        "///",
        "/// Historically these lived as `.lproj/Localizable.strings` files inside",
        "/// `Platinumaps.bundle`. Carrying them as a resource breaks the Flutter",
        "/// plugin's Swift Package Manager build, because Flutter's plugin",
        "/// injection treats the plugin package as a local override of an",
        "/// ephemeral copy that ALSO declares the same resource files — Xcode",
        "/// then refuses to resolve the package graph with \"duplicate rule\"",
        "/// errors. Embedding the strings sidesteps that entirely and keeps the",
        "/// SDK self-contained for every distribution channel (Swift Package",
        "/// Manager, CocoaPods, manual integration, Flutter plugin).",
        "enum PMLocalizedStrings {",
        "",
        "    static func string(forKey key: String) -> String {",
        "        let identifier = Bundle.main.preferredLocalizations.first",
        "            ?? Locale.current.identifier",
        "        let table = table(forLanguageCode: identifier)",
        "        return table[key] ?? englishTable[key] ?? key",
        "    }",
        "",
        "    private static func table(forLanguageCode code: String) -> [String: String] {",
        "        let primary = code.split(separator: \"-\").first.map(String.init)?.lowercased() ?? \"\"",
        "        switch primary {",
        "        case \"ja\":",
        "            return japaneseTable",
        "        case \"ko\":",
        "            return koreanTable",
        "        case \"zh\":",
        "            // Match Apple's BCP-47 forms (`zh-Hans-…`, `zh-Hant-…`) as well",
        "            // as the older legacy codes (`zh-CN`, `zh-TW`).",
        "            let lowered = code.lowercased()",
        "            if lowered.contains(\"hant\") || lowered.contains(\"tw\") || lowered.contains(\"hk\") || lowered.contains(\"mo\") {",
        "                return traditionalChineseTable",
        "            }",
        "            return simplifiedChineseTable",
        "        default:",
        "            return englishTable",
        "        }",
        "    }",
    ]

    for language in LANGUAGES:
        table_name = IOS_TABLE_NAMES[language]
        lines.append("")
        lines.append(f"    private static let {table_name}: [String: String] = [")
        for entry in entries:
            ios_key = entry.get("ios_key")
            if not ios_key:
                continue
            value = entry["translations"].get(language)
            if value is None:
                value = entry["translations"]["en"]
            lines.append(
                f'        "{swift_escape(ios_key)}": "{swift_escape(value)}",'
            )
        lines.append("    ]")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_android(entries: list[dict], language: str) -> str:
    """Generate one Android `strings.xml` for the given language."""
    lines = [
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
        "<!-- Generated by scripts/generate-strings.py. DO NOT EDIT.",
        "     Edit i18n/strings.yaml instead and re-run the generator. -->",
        "<resources>",
    ]
    for entry in entries:
        android_key = entry.get("android_key")
        if not android_key:
            continue
        value = entry["translations"].get(language)
        if value is None:
            value = entry["translations"]["en"]
        lines.append(
            f'    <string name="{android_key}">{xml_escape(value)}</string>'
        )
    lines.append("</resources>")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    entries = load_strings()

    swift_source = render_ios(entries)
    changed_files = []
    if write_if_changed(IOS_OUTPUT, swift_source):
        changed_files.append(IOS_OUTPUT)

    for language, subdir in ANDROID_VALUES_DIRS.items():
        xml_source = render_android(entries, language)
        for res_root in ANDROID_RES_ROOTS:
            path = res_root / subdir / "strings.xml"
            if write_if_changed(path, xml_source):
                changed_files.append(path)

    if changed_files:
        print("Updated:")
        for p in changed_files:
            print(f"  {p.relative_to(REPO_ROOT)}")
    else:
        print("All generated files already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
